//
// Created by root on 2021/6/19.
//

#ifndef MASTER_DEFS_H
#define MASTER_DEFS_H

#define GRAY_THRESH 3

#define IMAGEWIDTH      640
#define IMAGEHEIGHT     480

enum MISSION_STATE {NOTDEFINEDMISSION, DETECTING, NEARING, PICKING_UP, PUTTING_BACK};
enum TARGET_TYPE   {NOTDEFINEDTYPE, BATTERY, SPITBALL, PERICARP, BOTTLE, CUP};

#endif //MASTER_DEFS_H
